### Получить jwt
POST http://localhost:8080/jwt
Content-Type: application/json

{
  "login": "vitr",
  "rights": ["ROLE_ADMIN"]
}

> {%
    client.global.set("jwt", response.body);
%}

### Получить информацию о jwt
GET http://localhost:8080/secured/jwt
Authorization: Bearer {{jwt}}