spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

application:
  value: 150
  file: 'file:test.txt'

server:
  port: 8090
