spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
  security:
    user:
      name: admin
      password: secret123
      roles: ADMIN

application:
  value: 150
  file: 'file:test.txt'

#server:
#  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: ru.itmo.spring.lesson6.controller
