spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'

application:
  value: 150
  file: 'file:test.txt'

#server:
#  port: 8090
